name: PR Checks and Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run gen-schemas
    - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: npm run pack
    - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: actions/upload-artifact@v4
      with:
        name: dist zip
        path: dist.zip
